[package]
name = "ylex_helper"
description = "Makefile generator for YACC/LEX files"
version = "0.0.1"
edition = "2021"

[dependencies]
# argument parser
clap = "3.1.6"
# Run shell commands
run_script = "0.9.0"
