all:	flex bison compile

flex:	{LEX_FILE}
	flex --outfile=scanner.c {LEX_FILE}

bison:	{YACC_FILE}
	bison --defines=tokens.h --output=parser.c {YACC_FILE}

compile: scanner.c parser.c
	gcc -o {EXEC_NAME} scanner.c parser.c -ly -lfl

clean:
	rm -rf scanner.c parser.c tokens.h {EXEC_NAME}
